language: node_js
node_js:
  - "9"
services:
  - mongodb
env:
  - DBAUTH=test:pass@
before_script:
  - sleep 15
  - mongo test-msm --eval 'db.createUser({user:"test",pwd:"pass",roles:["readWrite"]});'
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
