language: node_js
node_js:
  - "10"
services:
  - mongodb
env:
  - DBAUTH=test:pass@
before_script:
  - sleep 15
  - mongo test-msm --eval 'db.createUser({user:"test",pwd:"pass",roles:["readWrite"]});'
script: "npm run test-travis"
after_success: npm run coverage